apiVersion: v1
kind: ConfigMap
metadata:
  name: jasper-config
  namespace: jaspersoft
data:
  DB_HOST: postgresql
  DB_NAME: jasperserver-k8s
  DB_PORT: "5432"
  DB_USER: postgres
  DB_PASSWORD: postgres
  JRS_LOAD_SAMPLES: "true"
  #KEYSTORE_SECRET_NAME: '"jasperserver-pro-jrsks"'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jasperserver-pro
  name: jasperserver-pro
  namespace: jaspersoft
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
  selector:
    app: jasperserver-pro
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: jasperserver-pro
  name: jasperserver-pro
  namespace: jaspersoft
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jasperserver-pro
      namespace: jaspersoft
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: jasper-config
        image: jasperserver-pro:7.5.0
        name: jasperserver-pro
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            #cpu: 200m
            memory: 6Gi
          requests:
            #cpu: 100m
            memory: 2Gi
        volumeMounts:
        - mountPath: /usr/local/share/jasperserver-pro/license
          name: license
          readOnly: true
        - mountPath: /usr/local/share/jasperserver-pro/keystore
          name: keystore-files-secret
          readOnly: true
        - mountPath: /usr/local/share/jasperserver-pro
          name: jasperserver-pro-volume
          readOnly: true
      initContainers:
      - envFrom:
        - configMapRef:
            name: jasper-config
        image: jasperserver-pro-cmdline:k8s-7.5.0
        name: init
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            #cpu: 200m
            memory: 3Gi
          requests:
            #cpu: 100m
            memory: 1Gi
        volumeMounts:
        - mountPath: /usr/local/share/jasperserver-pro/license
          name: license
          readOnly: true
        - mountPath: /usr/local/share/jasperserver-pro-secrets/jasperserver-pro-jrsks
          name: keystore-files-secret
          readOnly: true
        - mountPath: /usr/local/share/jasperserver-pro
          name: jasperserver-pro-volume
          readOnly: false
      serviceAccountName: jasper-robot
      volumes:
      - name: license
        secret:
          secretName: jasperserver-pro-license
      - name: keystore-files-secret
        secret:
          secretName: jasperserver-pro-jrsks
      - name: jasperserver-pro-volume
        emptyDir: {}
